spring:
  datasource:
    driver-class-name : com.mysql.jdbc.Driver
    url: jdbc:mysql://oracle-cloud.ran-ding.ga:3306/flowable-holidays?characterEncoding=UTF-8
    username: flowable
    password: flowable
logging:
  level:
    ROOT: info
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  #database-schema-update: true